.PHONY: generate build-project

generate:
	mkdir build
	make build-project

build-project:
	cd ./build && cmake .. && make --no-print-directory

#Spec your input SRS here
run:
	./build/lab1

